### ISSUE TITLE
The script does not work

### ISSUE THREAD

**Issue by GeoFSFlightDeck** [plopmaster/GeoFS-HD-Free#3]
When I paste in the code it does not work and refuses to load.
<img width="1440" alt="Screenshot 2024-06-16 at 09 34 06" src="https://github.com/plopmaster/GeoFS-HD-Free/assets/148737475/1b2a93b4-e213-42eb-a3e7-1e6fbb6e6684">

**Comment by plopmaster** [comment]
Dupe of #2
